### ISSUE TITLE
Failed to find a META6.json file

### ISSUE THREAD

**Issue by deePerl** [Leont/path-iterator#5]
When I use zef to install Path::Iterator I get this error:

`===> Extraction: Failed to find a META6.json file for Path::Iterator:ver<0.0.1>:auth<Leon Timmermans> -- failure is likely`

According to zef’s team this is because META6.json should be used in place of META.info

Regards.

**Comment by Leont** [comment]
Seems I forgot to push the commit that fixed this months ago :-o. Fixed now.
